nelmio_api_doc:
    documentation:
        info:
            title: Item API
            description: Dokumentacja REST API
            version: 1.0.0
    routes:
        path_patterns:
            - ^/v1/items