get_items:
    path:      /v1/items
    controller: Api\Application\Controller\ApiController::getItems
    methods: ['GET']

get_item:
    path:      /v1/items/{itemId}
    controller: Api\Application\Controller\ApiController::getItem
    methods: ['GET']
    requirements:
        itemId: '\d+'

add_item:
    path:      /v1/items
    controller: Api\Application\Controller\ApiController::addItem
    methods: ['POST']

update_item:
    path:      /v1/items/{itemId}
    controller: Api\Application\Controller\ApiController::updateItem
    methods: ['PATCH']
    requirements:
        itemId: '\d+'

remove_item:
    path:      /v1/items/{itemId}
    controller: Api\Application\Controller\ApiController::removeItem
    methods: ['DELETE']
    requirements:
        itemId: '\d+'